import {StyleSheet} from 'react-native';

const globalStyles=StyleSheet.create({
    app:{
        backgroundColor:'#f5f5f5',
        flex:1,
        
    },
    homeText:{
        fontSize:25,
        fontWeight:'bold',
        fontStyle:'italic',
        alignSelf:'center'
    },
    inPut:{
        padding:10,
        borderBottomWidth:1,
        borderRadius:8,
        margin:15
    },
    styleInPut:{
        flexDirection:'row',
        justifyContent:'space-between',
        padding:20,
        margin:18
    },
    logInButton:{
        borderWidth:1,
        marginTop:60,
        alignSelf:'center',
        borderRadius:80,
        backgroundColor:'#f4511e',
        shadowRadius:20,
        shadowOpacity:0.5,
        padding:12
        
    },
    signUp:{
        borderWidth:1,
        backgroundColor:'#f4511e',
        borderRadius:80,
        padding:12,
        shadowRadius:10,
        shadowOpacity:0.5,
        marginTop:40
    },
    textinPut:{
        color:'#fff',
        fontSize:18,
        fontWeight:'700',
        fontStyle:'italic'
    },
    signUpScreen:{
        marginTop:30,
        padding:20,
        backgroundColor:'#f5f5f5',
        flex:1,
    },
    signup_Input:{
        margin:20,
        borderBottomWidth:1,
        borderColor:'#808080'
    },
    signup_header:{
        fontSize:25,
        fontWeight:'500',
        fontStyle:'italic',
        marginHorizontal:100
    },
    signUp_Submit:{
        borderWidth:1,
        marginTop:40,
        alignSelf:'center',
        backgroundColor:'#f4511e',
        shadowRadius:10,
        shadowOpacity:0.5,
        borderRadius:80,
        padding:10,
    },
    signUp_Submit_text:{
        fontSize:18,
        fontWeight:'700', 
        color:'#fff' 
    },
    forgetPasswordStyle:{
        marginTop:150
    },
    Forget_Password_text:{
        fontSize:18,
        fontWeight:'500',
        color:'red',
        alignSelf:'center',
    },
    Forget_Password_email_enter:{
        marginTop:30,
        borderBottomWidth:1,
        borderRadius:4,
        marginHorizontal:8,
        padding:6
    },
    Forget_Password_submitt_style:{
        marginTop:40,
        borderWidth:1,
        padding:10,
        borderRadius:80,
        backgroundColor:'#f4511e',
        shadowRadius:10,
        shadowOpacity:0.5,
        alignSelf:'center'
    },
    Forget_Password_Submit_Font:{
        fontWeight:"700",
        fontSize:18,
        color:'#fff'
    },
    NewPassword_header:{
        marginTop:100
    },
    NewPassword_header_text:{
        fontSize:16,
        alignSelf:'center',
        color:'red',
        fontWeight:'500'
    },
    NewPassword_inPut:{
        marginTop:30,
        borderBottomWidth:1,
        borderRadius:2,
        marginHorizontal:10
    },
    NewPassword_Submit:{
        marginTop:40,
        borderWidth:1,
        alignSelf:'center',
        padding:10,
        borderRadius:80,
        backgroundColor:'#f4511e',
        shadowRadius:10,
        shadowOpacity:0.5,
    },
    NewPassword_font_Formats:{
        fontWeight:"700",
        fontSize:18,
        color:'#fff'
    },
    Home_list:{
        padding:20,
        marginBottom:20,
        backgroundColor:'rgba(255,255,255,.8)',
        borderRadius:16,
        shadowColor:'#000',
        shadowOffset:{
            height:10,
            width:0
        },
        shadowOpacity:.3,
        shadowRadius:20,
        flexDirection:"row"
    },
    Registartion_Page_Input:{
        borderBottomWidth:1,
        margin:14,
        borderColor:'#808080',
        padding:6
    },
    profile_Text:{
        fontSize:18,
        fontWeight:"700",
        paddingBottom:8
    }
});
export default globalStyles;
